approve_by_comment: true
approve_regex: '^[aA]pprove'
reject_regex: '^[rR]eject'
reset_on_push: true
author_approval: ignored
reviewers:
    -
        name: developers
        required: 1
        members:
            - atridgedcosta
            - allanhortle
            - dxinteractive
            - thepont
            - dancoates
        conditions:
            branches:
                - master  # only need to approve if merging to master
