const Lexicon = {
    noun: {
        list: [
            {base: "i", plural: "we"},
            {base: "mouse", plural: "mice"}
        ]
    },
    verb: {
        list: [
            {base: "arise", past: "arose", pp: "arisen"},
            {base: "awake", past: "awoke", pp: "awoken", ppPlural: "awaked"},
            {base: "be", past: "was", pastPlural: "were", pp: "been"},
            {base: "bear", past: "bore", pp: "born", ppPlural: "borne"},
            {base: "beat", past: "beat", pp: "beaten"},
            {base: "become", past: "became", pp: "become"},
            {base: "begin", past: "began", pp: "begun"},
            {base: "bend", past: "bent", pp: "bent"},
            {base: "bet", past: "bet", pp: "bet"},
            {base: "bid", past: "bade", pastPlural: "bid", pp: "bidden", ppPlural: "bid"},
            {base: "bind", past: "bound", pp: "bound"},
            {base: "bite", past: "bit", pp: "bitten"},
            {base: "bleed", past: "bled", pp: "bled"},
            {base: "blow", past: "blew", pp: "blown"},
            {base: "break", past: "broke", pp: "broken"},
            {base: "breed", past: "bred", pp: "bred"},
            {base: "bring", past: "brought", pp: "brought"},
            {base: "build", past: "built", pp: "built"},
            {base: "burn", past: "burned", pastPlural: "burnt", pp: "burned", ppPlural: "burnt"},
            {base: "burst", past: "burst", pp: "burst"},
            {base: "buy", past: "bought", pp: "bought"},
            {base: "cast", past: "cast", pp: "cast"},
            {base: "catch", past: "caught", pp: "caught"},
            {base: "choose", past: "chose", pp: "chosen"},
            {base: "come", past: "came", pp: "come"},
            {base: "cost", past: "cost", pp: "cost"},
            {base: "creep", past: "crept", pp: "crept"},
            {base: "cut", past: "cut", pp: "cut"},
            {base: "deal", past: "dealt", pp: "dealt"},
            {base: "dig", past: "dug", pp: "dug"},
            {base: "dive", past: "dived", pastPlural: "dove", pp: "dived"},
            {base: "do", past: "did", pp: "done"},
            {base: "draw", past: "drew", pp: "drawn"},
            {base: "dream", past: "dreamed", pastPlural: "dreamt", pp: "dreamed", ppPlural: "dreamt"},
            {base: "drink", past: "drank", pp: "drunk"},
            {base: "drive", past: "drove", pp: "driven"},
            {base: "dwell", past: "dwelt", pp: "dwelt"},
            {base: "eat", past: "ate", pp: "eaten"},
            {base: "fall", past: "fell", pp: "fallen"},
            {base: "feed", past: "fed", pp: "fed"},
            {base: "fight", past: "fought", pp: "fought"},
            {base: "find", past: "found", pp: "found"},
            {base: "flee", past: "fled", pp: "fled"},
            {base: "fly", past: "flew", pp: "flown"},
            {base: "forbid", past: "forbade", pastPlural: "forbad", pp: "forbidden"},
            {base: "forget", past: "forgot", pp: "forgotten"},
            {base: "forgive", past: "forgave", pp: "forgiven"},
            {base: "forsake", past: "forsook", pp: "forsaken"},
            {base: "freeze", past: "froze", pp: "frozen"},
            {base: "get", past: "got", pp: "gotten", ppPlural: "got"},
            {base: "give", past: "gave", pp: "given"},
            {base: "go", past: "went", pp: "gone"},
            {base: "grind", past: "ground", pp: "ground"},
            {base: "grow", past: "grew", pp: "grown"},
            {base: "hang", past: "hanged", pastPlural: "hung", pp: "hanged", ppPlural: "hung"},
            {base: "have", past: "had", pp: "had"},
            {base: "hear", past: "heard", pp: "heard"},
            {base: "hide", past: "hid", pp: "hidden"},
            {base: "hit", past: "hit", pp: "hit"},
            {base: "hold", past: "held", pp: "held"},
            {base: "hurt", past: "hurt", pp: "hurt"},
            {base: "keep", past: "kept", pp: "kept"},
            {base: "kneel", past: "knelt", pp: "knelt"},
            {base: "knit", past: "knitted", pastPlural: "knit", pp: "knitted", ppPlural: "knit"},
            {base: "know", past: "knew", pp: "known"},
            {base: "lay", past: "laid", pp: "laid"},
            {base: "lead", past: "led", pp: "led"},
            {base: "lean", past: "leaned", pastPlural: "leant"},
            {base: "leaned", past: "leant"},
            {base: "leap", past: "leaped", pastPlural: "leapt"},
            {base: "leaped", past:"leapt"},
            {base: "learn", past: "learned", pastPlural: "learnt", pp: "learned", ppPlural: "learnt"},
            {base: "leave", past: "left", pp: "left"},
            {base: "lend", past: "lent", pp: "lent"},
            {base: "let", past: "let", pp: "let"},
            {base: "lie", past: "lay", pp: "lain"},
            {base: "light", past: "lighted", pastPlural: "lit", pp: "lighted", ppPlural: "lit"},
            {base: "lose", past: "lost", pp: "lost"},
            {base: "make", past: "made", pp: "made"},
            {base: "mean", past: "meant", pp: "meant"},
            {base: "meet", past: "met", pp: "met"},
            {base: "mistake", past: "mistook", pp: "mistaken"},
            {base: "partake", past: "partook", pp: "partaken"},
            {base: "pay", past: "paid", pp: "paid"},
            {base: "put", past: "put", pp: "put"},
            {base: "read", past: "read", pp: "read"},
            {base: "rend", past: "rent", pp: "rent"},
            {base: "rid", past: "rid", pp: "rid"},
            {base: "ride", past: "rode", pp: "ridden"},
            {base: "rise", past: "rose", pp: "risen"},
            {base: "run", past: "ran", pp: "run"},
            {base: "say", past: "said", pp: "said"},
            {base: "see", past: "saw", pp: "seen"},
            {base: "seek", past: "sought", pp: "sought"},
            {base: "sell", past: "sold", pp: "sold"},
            {base: "send", past: "sent", pp: "sent"},
            {base: "set", past: "set", pp: "set"},
            {base: "shake", past: "shook", pp: "shaken"},
            {base: "shed", past: "shed", pp: "shed"},
            {base: "shine", past: "shone", pp: "shone"},
            {base: "shoot", past: "shot", pp: "shot"},
            {base: "shrink", past: "shrank", pp: "shrunk"},
            {base: "shut", past: "shut", pp: "shut"},
            {base: "sing", past: "sang", pp: "sung"},
            {base: "sink", past: "sank", pp: "sank"},
            {base: "sit", past: "sat", pp: "sat"},
            {base: "slay", past: "slew", pp: "slain"},
            {base: "sleep", past: "slept", pp: "slept"},
            {base: "slide", past: "slid", pp: "slid", ppPlural: "slidden"},
            {base: "sling", past: "slung", pp: "slung"},
            {base: "slit", past: "slit", pp: "slit"},
            {base: "speak", past: "spoke", pp: "spoken"},
            {base: "speed", past: "sped", pastPlural: "speeded", pp: "sped", ppPlural: "speeded"},
            {base: "spin", past: "spun", pp: "spun"},
            {base: "spit", past: "spat", pp: "spat"},
            {base: "split", past: "split", pp: "split"},
            {base: "spring", past: "sprang", pp: "sprung"},
            {base: "stand", past: "stood", pp: "stood"},
            {base: "steal", past: "stole", pp: "stolen"},
            {base: "stick", past: "stuck", pp: "stuck"},
            {base: "sting", past: "stung", pp: "stung"},
            {base: "stink", past: "stank", pp: "stunk"},
            {base: "stride", past: "strode", pp: "stridden"},
            {base: "strive", past: "strove", pp: "striven"},
            {base: "swear", past: "swore", pp: "sworn"},
            {base: "sweep", past: "swept", pp: "swept"},
            {base: "swim", past: "swam", pp: "swum"},
            {base: "swing", past: "swung", pp: "swung"},
            {base: "take", past: "took", pp: "taken"},
            {base: "teach", past: "taught", pp: "taught"},
            {base: "tear", past: "tore", pp: "torn"},
            {base: "tell", past: "told", pp: "told"},
            {base: "think", past: "thought", pp: "thought"},
            {base: "throw", past: "threw", pp: "thrown"},
            {base: "tread", past: "trod", pp: "trodden", ppPlural: "trod"},
            {base: "understand", past: "understood", pp: "understood"},
            {base: "upset", past: "upset", pp: "upset"},
            {base: "wake", past: "woke", pp: "woken", pastPlural: "waked"},
            {base: "wear", past: "wore", pp: "worn"},
            {base: "weave", past: "wove", pp: "woven"},
            {base: "weep", past: "wept", pp: "wept"},
            {base: "win", past: "won", pp: "won"},
            {base: "wind", past: "wound", pp: "wound"},
            {base: "wring", past: "wrung", pp: "wrung"},
            {base: "write", past: "wrote", pp: "written"}
        ]
    }
};

export default Lexicon;
