import React from 'react';
import Phraser from 'phraser';

export default (props) => {
    return <div>
        <h1>Phraser</h1>
        <p>Hello. This is not an autogenerated sentence. But perhaps someday it will be.</p>
    </div>;
}
